from dataclasses import replace
import json

import pytest
from jsonschema import Draft202012Validator

from driftguard.contracts.loader import PROJECT_ROOT
from driftguard.healing import PatchLifecycle, PatchOperation
from phase8_helpers import candidate


def test_tool_spec_patch_schema_accepts_generated_patch():
    schema = json.loads((PROJECT_ROOT / "benchmark/schemas/tool_spec_patch_schema_v1.json").read_text())
    Draft202012Validator(schema).validate(candidate().to_dict())


def test_healing_result_schema_accepts_formal_result():
    path = PROJECT_ROOT / "results/healing/healing_conformance_v1.json"
    if not path.exists():
        pytest.skip("formal conformance result is generated by the final validation command")
    schema = json.loads((PROJECT_ROOT / "benchmark/schemas/healing_result_schema_v1.json").read_text())
    Draft202012Validator(schema).validate(json.loads(path.read_text()))


def test_operation_requires_evidence():
    with pytest.raises(ValueError, match="cite visible evidence"):
        PatchOperation("add", "/x", 1, (), "NO_EVIDENCE")


def test_operation_rejects_invalid_rfc6902_name():
    with pytest.raises(ValueError, match="unsupported"):
        PatchOperation("merge", "/x", 1, ("EV1",), "BAD")


def test_patch_lifecycle_is_serialized():
    value = candidate().with_status(PatchLifecycle.STATIC_VALIDATED)
    assert value.to_dict()["lifecycle_status"] == "STATIC_VALIDATED"


def test_patch_rejects_unsupported_category():
    with pytest.raises(ValueError, match="unsupported drift"):
        replace(candidate(), drift_category="OTHER")

